### ISSUE TITLE
Where can I find the rest of the code for the Chefbot

### ISSUE THREAD

**Issue by pitosalas** [PacktPublishing/Learning-Robotics-using-Python-Second-Edition#3]
Specifically the code to run on the Launchpad? It should be several .c, .h and .cpp files. It seems like the code examples cited in the book are quite incomplete. We are actually trying to build a chefbot and would love a pointer to that code. We found this https://github.com/qboticslabs/Chefbot_ROS_pkg/tree/master/tiva_c_energia_code_final but it seems unauthorized and perhaps incomplete or buggy, I greatly appreciate your book and it's excellent content and would love to try and bring it over the finish line! THanks

**Comment by qboticslabs** [comment]
Hi @pitosalas The full firmware code for Tiva C Launchpad and Arduio has been updated in chapter 8.

**Comment by pitosalas** [comment]
Hi @qboticslabs long time no see! Thanks.
